version: '3'
services:
  web-client:
    image: ${WEB_APP_NAME}
    container_name: ${WEB_APP_NAME}
    hostname: ${WEB_APP_NAME}
    network_mode: platform
    restart: always
    build:
      context: ../
      args:
        - WORKSTATION=${WEB_WORKSTATION}
        - DEV_CERTIFICATES_ACTIVE=${WEB_DEV_CERTIFICATES_ACTIVE}
        - MAINTENANCE_MODE_ACTIVE=${WEB_MAINTENANCE_MODE_ACTIVE}
        - COOKIE_NAME=${WEB_COOKIE_NAME}
        - API_KEY=${WEB_API_KEY}
        - DOMAIN=${WEB_DOMAIN}
        - APIGW_PROTOCOL=${WEB_APIGW_PROTOCOL}
        - APIGW_HOST=${API_GATEWAY_NAME}
        - APIGW_PORT=${API_GATEWAY_PORT}
        - WS_PROTOCOL=${WEB_WS_PROTOCOL}
        - WS_HOST=${API_GATEWAY_NAME}
        - WS_PORT=${API_GATEWAY_PORT}
    volumes:
      - ../.yarn/cache:/usr/src/app/.yarn/cache
    ports:
      - 443:443/tcp
      - 443:443/udp
