openapi: 3.0.0
info:
  title: User
  description: |
    CRUD, check password
  version: 1.0.0

externalDocs:
  description: More
  url: https://platform.initialbyte.com/docs/api/user

servers:
  - url: https://localhost:8009/
    description: Local api-mock server
  - url: https://localhost/api/
    description: Local sandbox api-gateway server (uses test data)
  - url: https://sandbox.initialbyte.com/
    description: External sandbox server

tags:
- name: public
  description: Methods available from api-gateway without JWT
- name: protected
  description: Methods available from api-gateway with JWT
- name: private
  description: Methods available only from internal micro-services

paths:
  /user/checkpassword:
    post:
        tags:
          - private
        summary: Check password
        description: Check user's password to singing in
        responses:
          "200":
            description: Success Login
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

  /user/list:
    get:
        tags:
          - protected
        summary: View
        description: View info about one user
        responses:
          "200":
            description: Success Login
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

  /user:
    get:
        tags:
          - protected
        summary: View
        description: View info about one user
        responses:
          "200":
            description: Success Login
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

    post:
        tags:
          - protected
        summary: Create
        description: Create new user
        responses:
          "200":
            description: Success Login
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

    put:
        tags:
          - protected
        summary: Update
        description: Update an existing user
        responses:
          "200":
            description: Success Logout
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

    delete:
        tags:
          - protected
        summary: Delete
        description: Delete an existing user
        responses:
          "200":
            description: Success Logout
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

components:
  responses:
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not Found
    InternalServerError:
      description: Internal Server Error
    ServiceUnavailable:
      description: Service Unavailable

  securitySchemes:
    userAuth:
      type: apiKey
      name: JWT_ID
      in: header
