openapi: 3.0.0
info:
  title: Auth
  description: |
    Signin, signout
  version: 1.0.0

externalDocs:
  description: More
  url: https://platform.initialbyte.com/docs/api/auth

servers:
  - url: https://localhost:8009/
    description: Local api-mock server
  - url: https://localhost/api/
    description: Local sandbox api-gateway server (uses test data)
  - url: https://sandbox.initialbyte.com/
    description: External sandbox server

tags:
- name: public
  description: Methods available from api-gateway without JWT
- name: protected
  description: Methods available from api-gateway with JWT
- name: private
  description: Methods available only from internal micro-services

paths:
  /auth/signin:
    post:
        tags:
          - public
        summary: Login
        description: Login via login + password
        parameters:
          - in: query
            name: username
            description: user"s username
            required: true
            schema:
              type: string
          - in: query
            name: password
            description: user"s password
            required: true
            schema:
              type: string
          - in: query
            name: csrf
            schema:
              type: string
              default: dev
          - in: cookie
            name: fingerprint
            schema:
              type: string
              default: dev
        responses:
          "200":
            description: Success Login
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable

  /auth/signout:
    get:
        tags:
          - protected
        summary: Logout
        description: Remove cookie with JWT token
        parameters:
          - in: query
            name: csrf
            schema:
              type: string
              default: dev
          - in: cookie
            name: fingerprint
            schema:
              type: string
              default: dev
        responses:
          "200":
            description: Success Logout
          "401":
            description: Unauthorized
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
        security:
        - userAuth: []

components:
  responses:
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not Found
    InternalServerError:
      description: Internal Server Error
    ServiceUnavailable:
      description: Service Unavailable

  securitySchemes:
    userAuth:
      type: apiKey
      name: JWT_ID
      in: header
